
package org.de.metux.unitool.db;

import org.de.metux.util.StoreFile;
import org.de.metux.unitool.base.ObjectInfo;

public class StoreLibtoolObject
{
    public static void store(ObjectInfo inf, String lo_file)
    {
	String text = 
	    "# "+lo_file+" - a libtool object file\n"+
	    "# Generated by ltmain.sh - GNU libtool 1.5.0a\n"+
	    "#\n"+
	    "# Well, in fact it is generated by unitool's libtool emulation\n"+
	    "\n"+
	    "# Name of the PIC object\n"+
	    "pic_object='"+inf.object_pic+"'\n"+
	    "\n"+
	    "# Name of the non-PIC object\n"+
	    "non_pic_object='"+inf.object_nonpic+"'\n"+
	    "\n";
	
	StoreFile.store(lo_file,text);
    }    

    public static void store(ObjectInfo inf)
    {
	store(inf,inf.lo_file);    
    }
}
